/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dbservice.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dbservice.pb-c.h"
void   dbservice__create_schema_req__init
                     (Dbservice__CreateSchemaReq         *message)
{
  static const Dbservice__CreateSchemaReq init_value = DBSERVICE__CREATE_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t dbservice__create_schema_req__get_packed_size
                     (const Dbservice__CreateSchemaReq *message)
{
  assert(message->base.descriptor == &dbservice__create_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__create_schema_req__pack
                     (const Dbservice__CreateSchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__create_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__create_schema_req__pack_to_buffer
                     (const Dbservice__CreateSchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__create_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__CreateSchemaReq *
       dbservice__create_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__CreateSchemaReq *)
     protobuf_c_message_unpack (&dbservice__create_schema_req__descriptor,
                                allocator, len, data);
}
void   dbservice__create_schema_req__free_unpacked
                     (Dbservice__CreateSchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__create_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__create_schema_resp__init
                     (Dbservice__CreateSchemaResp         *message)
{
  static const Dbservice__CreateSchemaResp init_value = DBSERVICE__CREATE_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t dbservice__create_schema_resp__get_packed_size
                     (const Dbservice__CreateSchemaResp *message)
{
  assert(message->base.descriptor == &dbservice__create_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__create_schema_resp__pack
                     (const Dbservice__CreateSchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__create_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__create_schema_resp__pack_to_buffer
                     (const Dbservice__CreateSchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__create_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__CreateSchemaResp *
       dbservice__create_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__CreateSchemaResp *)
     protobuf_c_message_unpack (&dbservice__create_schema_resp__descriptor,
                                allocator, len, data);
}
void   dbservice__create_schema_resp__free_unpacked
                     (Dbservice__CreateSchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__create_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__query_schema_req__init
                     (Dbservice__QuerySchemaReq         *message)
{
  static const Dbservice__QuerySchemaReq init_value = DBSERVICE__QUERY_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t dbservice__query_schema_req__get_packed_size
                     (const Dbservice__QuerySchemaReq *message)
{
  assert(message->base.descriptor == &dbservice__query_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__query_schema_req__pack
                     (const Dbservice__QuerySchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__query_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__query_schema_req__pack_to_buffer
                     (const Dbservice__QuerySchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__query_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__QuerySchemaReq *
       dbservice__query_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__QuerySchemaReq *)
     protobuf_c_message_unpack (&dbservice__query_schema_req__descriptor,
                                allocator, len, data);
}
void   dbservice__query_schema_req__free_unpacked
                     (Dbservice__QuerySchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__query_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__query_schema_resp__init
                     (Dbservice__QuerySchemaResp         *message)
{
  static const Dbservice__QuerySchemaResp init_value = DBSERVICE__QUERY_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t dbservice__query_schema_resp__get_packed_size
                     (const Dbservice__QuerySchemaResp *message)
{
  assert(message->base.descriptor == &dbservice__query_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__query_schema_resp__pack
                     (const Dbservice__QuerySchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__query_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__query_schema_resp__pack_to_buffer
                     (const Dbservice__QuerySchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__query_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__QuerySchemaResp *
       dbservice__query_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__QuerySchemaResp *)
     protobuf_c_message_unpack (&dbservice__query_schema_resp__descriptor,
                                allocator, len, data);
}
void   dbservice__query_schema_resp__free_unpacked
                     (Dbservice__QuerySchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__query_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__drop_schema_req__init
                     (Dbservice__DropSchemaReq         *message)
{
  static const Dbservice__DropSchemaReq init_value = DBSERVICE__DROP_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t dbservice__drop_schema_req__get_packed_size
                     (const Dbservice__DropSchemaReq *message)
{
  assert(message->base.descriptor == &dbservice__drop_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__drop_schema_req__pack
                     (const Dbservice__DropSchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__drop_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__drop_schema_req__pack_to_buffer
                     (const Dbservice__DropSchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__drop_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__DropSchemaReq *
       dbservice__drop_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__DropSchemaReq *)
     protobuf_c_message_unpack (&dbservice__drop_schema_req__descriptor,
                                allocator, len, data);
}
void   dbservice__drop_schema_req__free_unpacked
                     (Dbservice__DropSchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__drop_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__drop_schema_resp__init
                     (Dbservice__DropSchemaResp         *message)
{
  static const Dbservice__DropSchemaResp init_value = DBSERVICE__DROP_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t dbservice__drop_schema_resp__get_packed_size
                     (const Dbservice__DropSchemaResp *message)
{
  assert(message->base.descriptor == &dbservice__drop_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__drop_schema_resp__pack
                     (const Dbservice__DropSchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__drop_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__drop_schema_resp__pack_to_buffer
                     (const Dbservice__DropSchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__drop_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__DropSchemaResp *
       dbservice__drop_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__DropSchemaResp *)
     protobuf_c_message_unpack (&dbservice__drop_schema_resp__descriptor,
                                allocator, len, data);
}
void   dbservice__drop_schema_resp__free_unpacked
                     (Dbservice__DropSchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__drop_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__put_kv_req__init
                     (Dbservice__PutKvReq         *message)
{
  static const Dbservice__PutKvReq init_value = DBSERVICE__PUT_KV_REQ__INIT;
  *message = init_value;
}
size_t dbservice__put_kv_req__get_packed_size
                     (const Dbservice__PutKvReq *message)
{
  assert(message->base.descriptor == &dbservice__put_kv_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__put_kv_req__pack
                     (const Dbservice__PutKvReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__put_kv_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__put_kv_req__pack_to_buffer
                     (const Dbservice__PutKvReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__put_kv_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__PutKvReq *
       dbservice__put_kv_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__PutKvReq *)
     protobuf_c_message_unpack (&dbservice__put_kv_req__descriptor,
                                allocator, len, data);
}
void   dbservice__put_kv_req__free_unpacked
                     (Dbservice__PutKvReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__put_kv_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__put_kv_resp__init
                     (Dbservice__PutKvResp         *message)
{
  static const Dbservice__PutKvResp init_value = DBSERVICE__PUT_KV_RESP__INIT;
  *message = init_value;
}
size_t dbservice__put_kv_resp__get_packed_size
                     (const Dbservice__PutKvResp *message)
{
  assert(message->base.descriptor == &dbservice__put_kv_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__put_kv_resp__pack
                     (const Dbservice__PutKvResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__put_kv_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__put_kv_resp__pack_to_buffer
                     (const Dbservice__PutKvResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__put_kv_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__PutKvResp *
       dbservice__put_kv_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__PutKvResp *)
     protobuf_c_message_unpack (&dbservice__put_kv_resp__descriptor,
                                allocator, len, data);
}
void   dbservice__put_kv_resp__free_unpacked
                     (Dbservice__PutKvResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__put_kv_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__get_kv_req__init
                     (Dbservice__GetKvReq         *message)
{
  static const Dbservice__GetKvReq init_value = DBSERVICE__GET_KV_REQ__INIT;
  *message = init_value;
}
size_t dbservice__get_kv_req__get_packed_size
                     (const Dbservice__GetKvReq *message)
{
  assert(message->base.descriptor == &dbservice__get_kv_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__get_kv_req__pack
                     (const Dbservice__GetKvReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__get_kv_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__get_kv_req__pack_to_buffer
                     (const Dbservice__GetKvReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__get_kv_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__GetKvReq *
       dbservice__get_kv_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__GetKvReq *)
     protobuf_c_message_unpack (&dbservice__get_kv_req__descriptor,
                                allocator, len, data);
}
void   dbservice__get_kv_req__free_unpacked
                     (Dbservice__GetKvReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__get_kv_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__get_kv_resp__init
                     (Dbservice__GetKvResp         *message)
{
  static const Dbservice__GetKvResp init_value = DBSERVICE__GET_KV_RESP__INIT;
  *message = init_value;
}
size_t dbservice__get_kv_resp__get_packed_size
                     (const Dbservice__GetKvResp *message)
{
  assert(message->base.descriptor == &dbservice__get_kv_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__get_kv_resp__pack
                     (const Dbservice__GetKvResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__get_kv_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__get_kv_resp__pack_to_buffer
                     (const Dbservice__GetKvResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__get_kv_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__GetKvResp *
       dbservice__get_kv_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__GetKvResp *)
     protobuf_c_message_unpack (&dbservice__get_kv_resp__descriptor,
                                allocator, len, data);
}
void   dbservice__get_kv_resp__free_unpacked
                     (Dbservice__GetKvResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__get_kv_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__del_kv_req__init
                     (Dbservice__DelKvReq         *message)
{
  static const Dbservice__DelKvReq init_value = DBSERVICE__DEL_KV_REQ__INIT;
  *message = init_value;
}
size_t dbservice__del_kv_req__get_packed_size
                     (const Dbservice__DelKvReq *message)
{
  assert(message->base.descriptor == &dbservice__del_kv_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__del_kv_req__pack
                     (const Dbservice__DelKvReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__del_kv_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__del_kv_req__pack_to_buffer
                     (const Dbservice__DelKvReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__del_kv_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__DelKvReq *
       dbservice__del_kv_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__DelKvReq *)
     protobuf_c_message_unpack (&dbservice__del_kv_req__descriptor,
                                allocator, len, data);
}
void   dbservice__del_kv_req__free_unpacked
                     (Dbservice__DelKvReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__del_kv_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dbservice__del_kv_resp__init
                     (Dbservice__DelKvResp         *message)
{
  static const Dbservice__DelKvResp init_value = DBSERVICE__DEL_KV_RESP__INIT;
  *message = init_value;
}
size_t dbservice__del_kv_resp__get_packed_size
                     (const Dbservice__DelKvResp *message)
{
  assert(message->base.descriptor == &dbservice__del_kv_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dbservice__del_kv_resp__pack
                     (const Dbservice__DelKvResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dbservice__del_kv_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dbservice__del_kv_resp__pack_to_buffer
                     (const Dbservice__DelKvResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dbservice__del_kv_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dbservice__DelKvResp *
       dbservice__del_kv_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dbservice__DelKvResp *)
     protobuf_c_message_unpack (&dbservice__del_kv_resp__descriptor,
                                allocator, len, data);
}
void   dbservice__del_kv_resp__free_unpacked
                     (Dbservice__DelKvResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dbservice__del_kv_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dbservice__create_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__CreateSchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__create_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange dbservice__create_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbservice__create_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.CreateSchemaReq",
  "CreateSchemaReq",
  "Dbservice__CreateSchemaReq",
  "dbservice",
  sizeof(Dbservice__CreateSchemaReq),
  1,
  dbservice__create_schema_req__field_descriptors,
  dbservice__create_schema_req__field_indices_by_name,
  1,  dbservice__create_schema_req__number_ranges,
  (ProtobufCMessageInit) dbservice__create_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__create_schema_resp__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__CreateSchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dbservice__CreateSchemaResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__CreateSchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__create_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange dbservice__create_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbservice__create_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.CreateSchemaResp",
  "CreateSchemaResp",
  "Dbservice__CreateSchemaResp",
  "dbservice",
  sizeof(Dbservice__CreateSchemaResp),
  3,
  dbservice__create_schema_resp__field_descriptors,
  dbservice__create_schema_resp__field_indices_by_name,
  1,  dbservice__create_schema_resp__number_ranges,
  (ProtobufCMessageInit) dbservice__create_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__query_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__QuerySchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__query_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange dbservice__query_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbservice__query_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.QuerySchemaReq",
  "QuerySchemaReq",
  "Dbservice__QuerySchemaReq",
  "dbservice",
  sizeof(Dbservice__QuerySchemaReq),
  1,
  dbservice__query_schema_req__field_descriptors,
  dbservice__query_schema_req__field_indices_by_name,
  1,  dbservice__query_schema_req__number_ranges,
  (ProtobufCMessageInit) dbservice__query_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__query_schema_resp__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__QuerySchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dbservice__QuerySchemaResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__QuerySchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meta",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__QuerySchemaResp, meta),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__query_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = code */
  3,   /* field[3] = meta */
  2,   /* field[2] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange dbservice__query_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dbservice__query_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.QuerySchemaResp",
  "QuerySchemaResp",
  "Dbservice__QuerySchemaResp",
  "dbservice",
  sizeof(Dbservice__QuerySchemaResp),
  4,
  dbservice__query_schema_resp__field_descriptors,
  dbservice__query_schema_resp__field_indices_by_name,
  1,  dbservice__query_schema_resp__number_ranges,
  (ProtobufCMessageInit) dbservice__query_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__drop_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DropSchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__drop_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange dbservice__drop_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dbservice__drop_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.DropSchemaReq",
  "DropSchemaReq",
  "Dbservice__DropSchemaReq",
  "dbservice",
  sizeof(Dbservice__DropSchemaReq),
  1,
  dbservice__drop_schema_req__field_descriptors,
  dbservice__drop_schema_req__field_indices_by_name,
  1,  dbservice__drop_schema_req__number_ranges,
  (ProtobufCMessageInit) dbservice__drop_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__drop_schema_resp__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DropSchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DropSchemaResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DropSchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__drop_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange dbservice__drop_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbservice__drop_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.DropSchemaResp",
  "DropSchemaResp",
  "Dbservice__DropSchemaResp",
  "dbservice",
  sizeof(Dbservice__DropSchemaResp),
  3,
  dbservice__drop_schema_resp__field_descriptors,
  dbservice__drop_schema_resp__field_indices_by_name,
  1,  dbservice__drop_schema_resp__number_ranges,
  (ProtobufCMessageInit) dbservice__drop_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__put_kv_req__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__PutKvReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__PutKvReq, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__PutKvReq, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__put_kv_req__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = schema_name */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange dbservice__put_kv_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbservice__put_kv_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.PutKvReq",
  "PutKvReq",
  "Dbservice__PutKvReq",
  "dbservice",
  sizeof(Dbservice__PutKvReq),
  3,
  dbservice__put_kv_req__field_descriptors,
  dbservice__put_kv_req__field_indices_by_name,
  1,  dbservice__put_kv_req__number_ranges,
  (ProtobufCMessageInit) dbservice__put_kv_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__put_kv_resp__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__PutKvResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dbservice__PutKvResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__PutKvResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__put_kv_resp__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = msg */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange dbservice__put_kv_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dbservice__put_kv_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.PutKvResp",
  "PutKvResp",
  "Dbservice__PutKvResp",
  "dbservice",
  sizeof(Dbservice__PutKvResp),
  3,
  dbservice__put_kv_resp__field_descriptors,
  dbservice__put_kv_resp__field_indices_by_name,
  1,  dbservice__put_kv_resp__number_ranges,
  (ProtobufCMessageInit) dbservice__put_kv_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__get_kv_req__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvReq, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__get_kv_req__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange dbservice__get_kv_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbservice__get_kv_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.GetKvReq",
  "GetKvReq",
  "Dbservice__GetKvReq",
  "dbservice",
  sizeof(Dbservice__GetKvReq),
  2,
  dbservice__get_kv_req__field_descriptors,
  dbservice__get_kv_req__field_indices_by_name,
  1,  dbservice__get_kv_req__number_ranges,
  (ProtobufCMessageInit) dbservice__get_kv_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__get_kv_resp__field_descriptors[5] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvResp, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvResp, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__GetKvResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__get_kv_resp__field_indices_by_name[] = {
  3,   /* field[3] = code */
  1,   /* field[1] = key */
  4,   /* field[4] = msg */
  0,   /* field[0] = schema_name */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange dbservice__get_kv_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dbservice__get_kv_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.GetKvResp",
  "GetKvResp",
  "Dbservice__GetKvResp",
  "dbservice",
  sizeof(Dbservice__GetKvResp),
  5,
  dbservice__get_kv_resp__field_descriptors,
  dbservice__get_kv_resp__field_indices_by_name,
  1,  dbservice__get_kv_resp__number_ranges,
  (ProtobufCMessageInit) dbservice__get_kv_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__del_kv_req__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvReq, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__del_kv_req__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange dbservice__del_kv_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dbservice__del_kv_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.DelKvReq",
  "DelKvReq",
  "Dbservice__DelKvReq",
  "dbservice",
  sizeof(Dbservice__DelKvReq),
  2,
  dbservice__del_kv_req__field_descriptors,
  dbservice__del_kv_req__field_indices_by_name,
  1,  dbservice__del_kv_req__number_ranges,
  (ProtobufCMessageInit) dbservice__del_kv_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dbservice__del_kv_resp__field_descriptors[5] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvResp, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dbservice__DelKvResp, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dbservice__del_kv_resp__field_indices_by_name[] = {
  0,   /* field[0] = code */
  3,   /* field[3] = key */
  1,   /* field[1] = msg */
  2,   /* field[2] = schema_name */
  4,   /* field[4] = value */
};
static const ProtobufCIntRange dbservice__del_kv_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dbservice__del_kv_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dbservice.DelKvResp",
  "DelKvResp",
  "Dbservice__DelKvResp",
  "dbservice",
  sizeof(Dbservice__DelKvResp),
  5,
  dbservice__del_kv_resp__field_descriptors,
  dbservice__del_kv_resp__field_indices_by_name,
  1,  dbservice__del_kv_resp__number_ranges,
  (ProtobufCMessageInit) dbservice__del_kv_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
